### ISSUE TITLE
Question how does one add url

### ISSUE THREAD

**Issue by davidbuckleyni** [tedd/ShortUrl#2]
Sorry the documentation just needs a tad goodness how does one add an url to the database to start off with?

**Comment by tedd** [comment]
Sorry I missed this one (by a whole month!).

The readme explains how to create, just use standard HTTP POST with JSON:
POST /Admin/Create
{
	"AccessToken": "$$TESTTOKEN$!!$CHANGEME$$",
	"Url": "http://mysite.com/$KEY$",
	"MetaData": "Put anything here, for example json",
	"Expires": "2018-01-01 15:30"
}

http://mysite.com/ is the URL to where you are hosting it and $KEY$ is where the id for that link will be replaced.
